export const state = {
  currentSessionId: "",
  sessions: [],
  conversation: [],
  uiMode: "chat",
  workspace: "chat",
  selectedTargets: [],
  selectedEditorText: "",
  currentSelectionRange: null,
  targetSeq: 0,
};

export const el = {
  main: document.getElementById("main"),
  sessionList: document.getElementById("sessionList"),
  chatLog: document.getElementById("chatLog"),
  chatInput: document.getElementById("chatInput"),
  sendBtn: document.getElementById("sendBtn"),
  chatTaskPanel: document.getElementById("chatTaskPanel"),
  chatTaskList: document.getElementById("chatTaskList"),
  toggleTaskBtn: document.getElementById("toggleTaskBtn"),
  newSessionBtn: document.getElementById("newSessionBtn"),
  emailLoginBtn: document.getElementById("emailLoginBtn"),
  authForms: document.getElementById("authForms"),
  emailLoginForm: document.getElementById("emailLoginForm"),
  emailRegisterForm: document.getElementById("emailRegisterForm"),
  loginEmailInput: document.getElementById("loginEmailInput"),
  loginPasswordInput: document.getElementById("loginPasswordInput"),
  registerNameInput: document.getElementById("registerNameInput"),
  registerEmailInput: document.getElementById("registerEmailInput"),
  registerPasswordInput: document.getElementById("registerPasswordInput"),
  registerConfirmPasswordInput: document.getElementById(
    "registerConfirmPasswordInput",
  ),
  registerCodeInput: document.getElementById("registerCodeInput"),
  sendCodeBtn: document.getElementById("sendCodeBtn"),
  toggleAuthModeBtn: document.getElementById("toggleAuthModeBtn"),
  reloginBtn: document.getElementById("reloginBtn"),
  logoutBtn: document.getElementById("logoutBtn"),
  accountMenu: document.getElementById("accountMenu"),
  accountSummary: document.getElementById("accountSummary"),
  userCard: document.getElementById("userCard"),
  editorPanel: document.getElementById("editorPanel"),
  editor: document.getElementById("editor"),
  rewriteSelectionBtn: document.getElementById("rewriteSelectionBtn"),
  saveLarkBtn: document.getElementById("saveLarkBtn"),
  workspaceTag: document.getElementById("workspaceTag"),
  contextBox: document.getElementById("contextBox"),
  selectionQuickAction: document.getElementById("selectionQuickAction"),
  markSelectionBtn: document.getElementById("markSelectionBtn"),
};
